import type { AddEvidenceInput, DataLayerProvider, Evidence, EvidenceListInput, EvidenceStore, GraphEdge, GraphNode, GraphStore, GraphTraversal, JsonObject, JsonValue, NeighborsInput, PlanetScope, ProviderSchemaMap, TraverseInput, UpdateEdgeInput, UpdateNodeInput } from "@unknown-planet/core";

export interface SQLiteStatement { run(...values: unknown[]): { changes: number; lastInsertRowid: number | bigint }; get(...values: unknown[]): unknown; all(...values: unknown[]): unknown[] }
/** Structural subset implemented by better-sqlite3 Database. */
export interface SQLiteDatabase { exec(sql: string): unknown; prepare(sql: string): SQLiteStatement }

const scopeId = (scope?: PlanetScope) => JSON.stringify([scope?.tenantId ?? "default", scope?.workspaceId ?? null]);
const schema = `
PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS up_nodes(scope_id TEXT NOT NULL,id TEXT NOT NULL,type TEXT NOT NULL,name TEXT NOT NULL,properties TEXT NOT NULL,embedding TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,PRIMARY KEY(scope_id,id));
CREATE TABLE IF NOT EXISTS up_edges(scope_id TEXT NOT NULL,id TEXT NOT NULL,source_id TEXT NOT NULL,target_id TEXT NOT NULL,relation TEXT NOT NULL,properties TEXT NOT NULL,confidence REAL,valid_from TEXT,valid_to TEXT,status TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,PRIMARY KEY(scope_id,id),FOREIGN KEY(scope_id,source_id) REFERENCES up_nodes(scope_id,id) ON DELETE CASCADE,FOREIGN KEY(scope_id,target_id) REFERENCES up_nodes(scope_id,id) ON DELETE CASCADE,CHECK(confidence IS NULL OR confidence BETWEEN 0 AND 1),CHECK(valid_from IS NULL OR valid_to IS NULL OR valid_to>valid_from));
CREATE INDEX IF NOT EXISTS up_edges_source_idx ON up_edges(scope_id,source_id,relation);
CREATE INDEX IF NOT EXISTS up_edges_target_idx ON up_edges(scope_id,target_id,relation);
CREATE TABLE IF NOT EXISTS up_evidence(scope_id TEXT NOT NULL,id TEXT NOT NULL,edge_id TEXT NOT NULL,document_id TEXT,source_id TEXT,chunk_id TEXT,source_type TEXT,extractor TEXT NOT NULL,confidence REAL,direction TEXT NOT NULL,strength REAL,metadata TEXT NOT NULL,created_at TEXT NOT NULL,PRIMARY KEY(scope_id,id),FOREIGN KEY(scope_id,edge_id) REFERENCES up_edges(scope_id,id) ON DELETE CASCADE,CHECK(document_id IS NOT NULL OR source_id IS NOT NULL),CHECK(confidence IS NULL OR confidence BETWEEN 0 AND 1),CHECK(strength IS NULL OR strength BETWEEN 0 AND 1));
CREATE INDEX IF NOT EXISTS up_evidence_edge_idx ON up_evidence(scope_id,edge_id,created_at,id);
`;
type NodeRow = { scope_id: string; id: string; type: string; name: string; properties: string; embedding: string | null; created_at: string; updated_at: string };
type EdgeRow = { id: string; source_id: string; target_id: string; relation: string; properties: string; confidence: number | null; valid_from: string | null; valid_to: string | null; status: GraphEdge["status"]; created_at: string; updated_at: string };
type EvidenceRow = { id: string; edge_id: string; document_id: string | null; source_id: string | null; chunk_id: string | null; source_type: string | null; extractor: string; confidence: number | null; direction: Evidence["direction"]; strength: number | null; metadata: string; created_at: string };
const parse = <T>(value: string): T => JSON.parse(value) as T;
const toNode = (row: NodeRow): GraphNode => ({ id: row.id, type: row.type, name: row.name, properties: parse<JsonObject>(row.properties), embedding: row.embedding ? parse<number[]>(row.embedding) : undefined, createdAt: new Date(row.created_at), updatedAt: new Date(row.updated_at) });
const toEdge = (row: EdgeRow): GraphEdge => ({ id: row.id, sourceId: row.source_id, targetId: row.target_id, relation: row.relation, properties: parse<JsonObject>(row.properties), confidence: row.confidence ?? undefined, validFrom: row.valid_from ? new Date(row.valid_from) : undefined, validTo: row.valid_to ? new Date(row.valid_to) : undefined, status: row.status, createdAt: new Date(row.created_at), updatedAt: new Date(row.updated_at) });
const toEvidence = (row: EvidenceRow): Evidence => ({ id: row.id, edgeId: row.edge_id, documentId: row.document_id ?? undefined, sourceId: row.source_id ?? undefined, chunkId: row.chunk_id ?? undefined, sourceType: row.source_type ?? undefined, extractor: row.extractor, confidence: row.confidence ?? undefined, direction: row.direction, strength: row.strength ?? undefined, metadata: parse<JsonObject>(row.metadata), createdAt: new Date(row.created_at) });

export class SQLiteGraphStore implements GraphStore {
  constructor(private readonly db: SQLiteDatabase) {}
  async createNode(input: { id?: string; type: string; name: string; properties?: JsonObject; embedding?: number[]; scope?: PlanetScope }): Promise<GraphNode> { const now = new Date().toISOString(); const value = { id: input.id ?? crypto.randomUUID(), scope_id: scopeId(input.scope), type: input.type, name: input.name, properties: JSON.stringify(input.properties ?? {}), embedding: input.embedding ? JSON.stringify(input.embedding) : null, created_at: now, updated_at: now }; this.db.prepare("INSERT INTO up_nodes(scope_id,id,type,name,properties,embedding,created_at,updated_at) VALUES(@scope_id,@id,@type,@name,@properties,@embedding,@created_at,@updated_at)").run(value); return toNode(value); }
  async getNode(id: string, scope?: PlanetScope): Promise<GraphNode | null> { const row = this.db.prepare("SELECT * FROM up_nodes WHERE scope_id=? AND id=?").get(scopeId(scope), id) as NodeRow | undefined; return row ? toNode(row) : null; }
  async updateNode(id: string, input: UpdateNodeInput): Promise<GraphNode | null> { const current = await this.getNode(id, input.scope); if (!current) return null; const next = { type: input.type ?? current.type, name: input.name ?? current.name, properties: input.properties ?? current.properties, embedding: input.embedding === null ? undefined : input.embedding ?? current.embedding, updatedAt: new Date() }; this.db.prepare("UPDATE up_nodes SET type=?,name=?,properties=?,embedding=?,updated_at=? WHERE scope_id=? AND id=?").run(next.type, next.name, JSON.stringify(next.properties), next.embedding ? JSON.stringify(next.embedding) : null, next.updatedAt.toISOString(), scopeId(input.scope), id); return this.getNode(id, input.scope); }
  async deleteNode(id: string, scope?: PlanetScope): Promise<boolean> { return this.db.prepare("DELETE FROM up_nodes WHERE scope_id=? AND id=?").run(scopeId(scope), id).changes > 0; }
  async createEdge(input: { id?: string; from: string; to: string; relation: string; properties?: JsonObject; confidence?: number; validFrom?: Date; validTo?: Date; status?: GraphEdge["status"]; scope?: PlanetScope }): Promise<GraphEdge> { const now = new Date().toISOString(); const value = { id: input.id ?? crypto.randomUUID(), scope_id: scopeId(input.scope), source_id: input.from, target_id: input.to, relation: input.relation, properties: JSON.stringify(input.properties ?? {}), confidence: input.confidence ?? null, valid_from: input.validFrom?.toISOString() ?? null, valid_to: input.validTo?.toISOString() ?? null, status: input.status ?? "candidate", created_at: now, updated_at: now }; this.db.prepare("INSERT INTO up_edges(scope_id,id,source_id,target_id,relation,properties,confidence,valid_from,valid_to,status,created_at,updated_at) VALUES(@scope_id,@id,@source_id,@target_id,@relation,@properties,@confidence,@valid_from,@valid_to,@status,@created_at,@updated_at)").run(value); return toEdge(value); }
  async getEdge(id: string, scope?: PlanetScope): Promise<GraphEdge | null> { const row = this.db.prepare("SELECT * FROM up_edges WHERE scope_id=? AND id=?").get(scopeId(scope), id) as EdgeRow | undefined; return row ? toEdge(row) : null; }
  async updateEdge(id: string, input: UpdateEdgeInput): Promise<GraphEdge | null> { const current = await this.getEdge(id, input.scope); if (!current) return null; const next = { confidence: input.confidence ?? current.confidence ?? null, status: input.status ?? current.status ?? "candidate", validFrom: input.validFrom === null ? null : input.validFrom ?? current.validFrom, validTo: input.validTo === null ? null : input.validTo ?? current.validTo, properties: input.properties ?? current.properties }; this.db.prepare("UPDATE up_edges SET confidence=?,status=?,valid_from=?,valid_to=?,properties=?,updated_at=? WHERE scope_id=? AND id=?").run(next.confidence, next.status, next.validFrom?.toISOString() ?? null, next.validTo?.toISOString() ?? null, JSON.stringify(next.properties), new Date().toISOString(), scopeId(input.scope), id); return this.getEdge(id, input.scope); }
  async deleteEdge(id: string, scope?: PlanetScope): Promise<boolean> { return this.db.prepare("DELETE FROM up_edges WHERE scope_id=? AND id=?").run(scopeId(scope), id).changes > 0; }
  async neighbors(input: NeighborsInput): Promise<GraphEdge[]> { const direction = input.direction ?? "both"; const endpoint = direction === "outbound" ? "source_id=?" : direction === "inbound" ? "target_id=?" : "(source_id=? OR target_id=?)"; const values: unknown[] = [scopeId(input.scope), input.nodeId]; if (direction === "both") values.push(input.nodeId); let where = `scope_id=? AND ${endpoint}`; if (input.relation) { where += " AND relation=?"; values.push(input.relation); } if (input.asOf) { where += " AND (valid_from IS NULL OR valid_from<=?) AND (valid_to IS NULL OR valid_to>?)"; values.push(input.asOf.toISOString(), input.asOf.toISOString()); } values.push(Math.max(1, Math.min(input.limit ?? 100, 10000))); return (this.db.prepare(`SELECT * FROM up_edges WHERE ${where} ORDER BY created_at,id LIMIT ?`).all(...values) as EdgeRow[]).map(toEdge); }
  async traverse(input: TraverseInput): Promise<GraphTraversal> { const max = Math.max(1, Math.min(input.limit ?? 1000, 10000)); const depths = new Map(input.startIds.slice(0, max).map((id) => [id, 0])); const edges = new Map<string, GraphEdge>(); let frontier = [...depths.keys()]; for (let depth = 1; depth <= input.depth && frontier.length && depths.size < max; depth++) { const next: string[] = []; for (const id of frontier) for (const edge of await this.neighbors({ nodeId: id, direction: input.direction, relation: input.relation, asOf: input.asOf, limit: max, scope: input.scope })) { edges.set(edge.id, edge); const target = edge.sourceId === id ? edge.targetId : edge.sourceId; if (!depths.has(target) && depths.size < max) { depths.set(target, depth); next.push(target); } } frontier = next; } const nodes = (await Promise.all([...depths.keys()].map((id) => this.getNode(id, input.scope)))).filter((item): item is GraphNode => item !== null); return { nodes, edges: [...edges.values()], depthByNode: Object.fromEntries(depths) }; }
  async searchNodes(input: { query: string; limit?: number; scope?: PlanetScope }): Promise<GraphNode[]> { const rows = this.db.prepare("SELECT * FROM up_nodes WHERE scope_id=? AND instr(lower(name),lower(?))>0 ORDER BY name,id LIMIT ?").all(scopeId(input.scope), input.query, Math.max(1, Math.min(input.limit ?? 20, 1000))) as NodeRow[]; return rows.map(toNode); }
}

export class SQLiteEvidenceStore implements EvidenceStore {
  constructor(private readonly db: SQLiteDatabase) {}
  async add(input: AddEvidenceInput): Promise<Evidence> { if (!input.documentId && !input.sourceId) throw new Error("Evidence requires a documentId or sourceId."); const value: EvidenceRow & { scope_id: string } = { scope_id: scopeId(input.scope), id: input.id ?? crypto.randomUUID(), edge_id: input.edgeId, document_id: input.documentId ?? null, source_id: input.sourceId ?? null, chunk_id: input.chunkId ?? null, source_type: input.sourceType ?? null, extractor: input.extractor, confidence: input.confidence ?? null, direction: input.direction ?? "support", strength: input.strength ?? input.confidence ?? null, metadata: JSON.stringify(input.metadata ?? {}), created_at: new Date().toISOString() }; this.db.prepare("INSERT INTO up_evidence(scope_id,id,edge_id,document_id,source_id,chunk_id,source_type,extractor,confidence,direction,strength,metadata,created_at) VALUES(@scope_id,@id,@edge_id,@document_id,@source_id,@chunk_id,@source_type,@extractor,@confidence,@direction,@strength,@metadata,@created_at)").run(value); return toEvidence(value); }
  async list(input: EvidenceListInput): Promise<Evidence[]> { const clauses = ["scope_id=?"]; const values: unknown[] = [scopeId(input.scope)]; if (input.edgeId) { clauses.push("edge_id=?"); values.push(input.edgeId); } if (input.edgeIds?.length) { clauses.push(`edge_id IN (${input.edgeIds.map(() => "?").join(",")})`); values.push(...input.edgeIds); } if (input.documentId) { clauses.push("document_id=?"); values.push(input.documentId); } if (input.sourceId) { clauses.push("source_id=?"); values.push(input.sourceId); } values.push(Math.max(1, Math.min(input.limit ?? 100, 10000))); return (this.db.prepare(`SELECT * FROM up_evidence WHERE ${clauses.join(" AND ")} ORDER BY created_at,id LIMIT ?`).all(...values) as EvidenceRow[]).map(toEvidence); }
  async listPage(input: EvidenceListInput & { afterId?: string }): Promise<{ items: Evidence[]; hasMore: boolean }> {
    const limit = Math.max(1, Math.min(input.limit ?? 100, 500));
    const clauses = ["scope_id=?"]; const values: unknown[] = [scopeId(input.scope)];
    if (input.edgeId) { clauses.push("edge_id=?"); values.push(input.edgeId); }
    if (input.edgeIds?.length) { clauses.push(`edge_id IN (${input.edgeIds.map(() => "?").join(",")})`); values.push(...input.edgeIds); }
    if (input.documentId) { clauses.push("document_id=?"); values.push(input.documentId); }
    if (input.sourceId) { clauses.push("source_id=?"); values.push(input.sourceId); }
    if (input.afterId) { clauses.push("id>?"); values.push(input.afterId); }
    values.push(limit + 1);
    const rows = this.db.prepare(`SELECT * FROM up_evidence WHERE ${clauses.join(" AND ")} ORDER BY id LIMIT ?`).all(...values) as EvidenceRow[];
    return { items: rows.slice(0, limit).map(toEvidence), hasMore: rows.length > limit };
  }
  async deleteByDocument(input: { documentId: string; scope?: PlanetScope }): Promise<number> { return this.db.prepare("DELETE FROM up_evidence WHERE scope_id=? AND document_id=?").run(scopeId(input.scope), input.documentId).changes; }
  async deleteByChunks(input: { chunkIds: string[]; scope?: PlanetScope }): Promise<number> { if (!input.chunkIds.length) return 0; return this.db.prepare(`DELETE FROM up_evidence WHERE scope_id=? AND chunk_id IN (${input.chunkIds.map(() => "?").join(",")})`).run(scopeId(input.scope), ...input.chunkIds).changes; }
}

function schemaSQLiteDatabase(database: SQLiteDatabase, schemas: ProviderSchemaMap = {}): SQLiteDatabase {
  const configured = { graph: schemas.graph, evidence: schemas.evidence };
  for (const [feature, namespace] of Object.entries(configured)) if (namespace !== undefined && !/^[A-Za-z_][A-Za-z0-9_]*$/.test(namespace)) throw new Error(`SQLite ${feature} namespace must be a simple identifier.`);
  const names: Record<string, string> = {};
  for (const table of ["nodes", "edges", "evidence"] as const) {
    const feature = table === "evidence" ? "evidence" : "graph";
    names[`up_${table}`] = configured[feature] ? `${configured[feature]}_${table}` : `up_${table}`;
  }
  names.up_edges_source_idx = configured.graph ? `${configured.graph}_edges_source_idx` : "up_edges_source_idx";
  names.up_edges_target_idx = configured.graph ? `${configured.graph}_edges_target_idx` : "up_edges_target_idx";
  names.up_evidence_edge_idx = configured.evidence ? `${configured.evidence}_evidence_edge_idx` : "up_evidence_edge_idx";
  const route = (sql: string) => sql.replace(/\b(up_nodes|up_edges|up_evidence|up_edges_source_idx|up_edges_target_idx|up_evidence_edge_idx)\b/g, (name) => names[name]!);
  return { exec: (sql) => database.exec(route(sql)), prepare: (sql) => database.prepare(route(sql)) };
}

export function createSQLiteProvider(input: { id?: string; database: SQLiteDatabase; schemas?: ProviderSchemaMap }): DataLayerProvider {
  const database = schemaSQLiteDatabase(input.database, input.schemas);
  database.exec(schema);
  return { id: input.id ?? "sqlite", graph: new SQLiteGraphStore(database), evidence: new SQLiteEvidenceStore(database) };
}
