import type { AddEvidenceInput, DataLayerProvider, Evidence, EvidenceListInput, EvidenceStore, GraphEdge, GraphNode, GraphStore, GraphTraversal, JsonObject, NeighborsInput, PlanetScope, ProviderSchemaMap, TraverseInput, UpdateEdgeInput, UpdateNodeInput } from "@unknown-planet/core";

interface Neo4jRecord { get(key: string): unknown }
interface Neo4jResult { records: Neo4jRecord[] }
export interface Neo4jSession { run(query: string, parameters?: Record<string, unknown>): Promise<Neo4jResult>; close(): Promise<void> }
/** Structural subset of the official neo4j-driver Driver. */
export interface Neo4jDriver { session(config?: { database?: string }): Neo4jSession }

const scopeId = (scope?: PlanetScope) => JSON.stringify([scope?.tenantId ?? "default", scope?.workspaceId ?? null]);
const dateString = (value: unknown): string | undefined => typeof value === "string" ? value : undefined;
const props = (value: unknown): Record<string, unknown> => {
  if (!value || typeof value !== "object") return {};
  const record = value as Record<string, unknown>;
  return record.properties && typeof record.properties === "object" ? record.properties as Record<string, unknown> : record;
};
const json = <T>(value: unknown, fallback: T): T => { if (typeof value !== "string") return fallback; try { return JSON.parse(value) as T; } catch { return fallback; } };
const toNode = (raw: unknown): GraphNode => { const p = props(raw); return { id: String(p.id), type: String(p.type), name: String(p.name), properties: json<JsonObject>(p.propertiesJson, {}), embedding: json<number[] | undefined>(p.embeddingJson, undefined), createdAt: new Date(dateString(p.createdAt) ?? 0), updatedAt: new Date(dateString(p.updatedAt) ?? 0) }; };
const toEdge = (raw: unknown): GraphEdge => { const p = props(raw); return { id: String(p.id), sourceId: String(p.sourceId), targetId: String(p.targetId), relation: String(p.relation), properties: json<JsonObject>(p.propertiesJson, {}), confidence: typeof p.confidence === "number" ? p.confidence : undefined, validFrom: dateString(p.validFrom) ? new Date(dateString(p.validFrom)!) : undefined, validTo: dateString(p.validTo) ? new Date(dateString(p.validTo)!) : undefined, status: (p.status as GraphEdge["status"]) ?? "candidate", createdAt: new Date(dateString(p.createdAt) ?? 0), updatedAt: new Date(dateString(p.updatedAt) ?? 0) }; };
const toEvidence = (raw: unknown): Evidence => { const p = props(raw); return { id: String(p.id), edgeId: String(p.edgeId), documentId: typeof p.documentId === "string" ? p.documentId : undefined, sourceId: typeof p.sourceId === "string" ? p.sourceId : undefined, chunkId: typeof p.chunkId === "string" ? p.chunkId : undefined, sourceType: typeof p.sourceType === "string" ? p.sourceType : undefined, extractor: String(p.extractor), confidence: typeof p.confidence === "number" ? p.confidence : undefined, direction: (p.direction as Evidence["direction"]) ?? "support", strength: typeof p.strength === "number" ? p.strength : undefined, metadata: json<JsonObject>(p.metadataJson, {}), createdAt: new Date(dateString(p.createdAt) ?? 0) }; };

type Neo4jNamespaces = { graph?: string; evidence?: string };
function neo4jLabels(namespaces: Neo4jNamespaces = {}) {
  for (const [feature, value] of Object.entries(namespaces)) if (value !== undefined && !/^[A-Za-z_][A-Za-z0-9_]*$/.test(value)) throw new Error(`Neo4j ${feature} namespace must be a simple identifier.`);
  return { UPNode: namespaces.graph ? `${namespaces.graph}_UPNode` : "UPNode", UP_EDGE: namespaces.graph ? `${namespaces.graph}_UP_EDGE` : "UP_EDGE", UPEvidence: namespaces.evidence ? `${namespaces.evidence}_UPEvidence` : "UPEvidence" };
}
abstract class Neo4jStore { constructor(protected readonly driver: Neo4jDriver, protected readonly database?: string, private readonly namespaces: Neo4jNamespaces = {}) {} protected async query(query: string, params: Record<string, unknown> = {}): Promise<Neo4jResult> { const labels = neo4jLabels(this.namespaces); const routed = query.replace(/\b(UPNode|UP_EDGE|UPEvidence)\b/g, (label) => labels[label as keyof typeof labels]); const session = this.driver.session(this.database ? { database: this.database } : undefined); try { return await session.run(routed, params); } finally { await session.close(); } } }

export class Neo4jGraphStore extends Neo4jStore implements GraphStore {
  constructor(driver: Neo4jDriver, database?: string, namespaces: Neo4jNamespaces = {}) { super(driver, database, namespaces); }
  async createNode(input: { id?: string; type: string; name: string; properties?: JsonObject; embedding?: number[]; scope?: PlanetScope }): Promise<GraphNode> { const value = { id: input.id ?? crypto.randomUUID(), scopeId: scopeId(input.scope), type: input.type, name: input.name, propertiesJson: JSON.stringify(input.properties ?? {}), embeddingJson: input.embedding ? JSON.stringify(input.embedding) : null, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }; const result = await this.query("CREATE (n:UPNode $value) RETURN n AS node", { value }); return toNode(result.records[0]!.get("node")); }
  async getNode(id: string, scope?: PlanetScope): Promise<GraphNode | null> { const result = await this.query("MATCH (n:UPNode {id:$id,scopeId:$scopeId}) RETURN n AS node", { id, scopeId: scopeId(scope) }); return result.records[0] ? toNode(result.records[0].get("node")) : null; }
  async updateNode(id: string, input: UpdateNodeInput): Promise<GraphNode | null> { const current = await this.getNode(id, input.scope); if (!current) return null; const next = { type: input.type ?? current.type, name: input.name ?? current.name, propertiesJson: JSON.stringify(input.properties ?? current.properties), embeddingJson: input.embedding === null ? null : JSON.stringify(input.embedding ?? current.embedding ?? null), updatedAt: new Date().toISOString() }; const result = await this.query("MATCH (n:UPNode {id:$id,scopeId:$scopeId}) SET n += $value RETURN n AS node", { id, scopeId: scopeId(input.scope), value: next }); return result.records[0] ? toNode(result.records[0].get("node")) : null; }
  async deleteNode(id: string, scope?: PlanetScope): Promise<boolean> { const scopeKey = scopeId(scope); const edges = await this.query("MATCH (n:UPNode {id:$id,scopeId:$scopeId}) OPTIONAL MATCH (n)-[r:UP_EDGE]-() RETURN collect(r.id) AS ids", { id, scopeId: scopeKey }); if (!edges.records[0]) return false; const ids = edges.records[0].get("ids") as string[]; if (ids.length) await this.query("MATCH (e:UPEvidence {scopeId:$scopeId}) WHERE e.edgeId IN $ids DETACH DELETE e", { scopeId: scopeKey, ids }); const result = await this.query("MATCH (n:UPNode {id:$id,scopeId:$scopeId}) DETACH DELETE n RETURN count(*) AS count", { id, scopeId: scopeKey }); return Number(result.records[0]?.get("count") ?? 0) > 0; }
  async createEdge(input: { id?: string; from: string; to: string; relation: string; properties?: JsonObject; confidence?: number; validFrom?: Date; validTo?: Date; status?: GraphEdge["status"]; scope?: PlanetScope }): Promise<GraphEdge> { const id = input.id ?? crypto.randomUUID(); const scopeKey = scopeId(input.scope); const now = new Date().toISOString(); const value = { id, scopeId: scopeKey, sourceId: input.from, targetId: input.to, relation: input.relation, propertiesJson: JSON.stringify(input.properties ?? {}), confidence: input.confidence ?? null, validFrom: input.validFrom?.toISOString() ?? null, validTo: input.validTo?.toISOString() ?? null, status: input.status ?? "candidate", createdAt: now, updatedAt: now }; const result = await this.query("MATCH (s:UPNode {id:$from,scopeId:$scopeId}),(t:UPNode {id:$to,scopeId:$scopeId}) CREATE (s)-[r:UP_EDGE $value]->(t) RETURN r AS edge", { from: input.from, to: input.to, scopeId: scopeKey, value }); if (!result.records[0]) throw new Error("Cannot create an edge unless both endpoint nodes exist in this scope."); return toEdge(result.records[0].get("edge")); }
  async getEdge(id: string, scope?: PlanetScope): Promise<GraphEdge | null> { const result = await this.query("MATCH ()-[r:UP_EDGE {id:$id,scopeId:$scopeId}]->() RETURN r AS edge", { id, scopeId: scopeId(scope) }); return result.records[0] ? toEdge(result.records[0].get("edge")) : null; }
  async updateEdge(id: string, input: UpdateEdgeInput): Promise<GraphEdge | null> { const current = await this.getEdge(id, input.scope); if (!current) return null; const next = { confidence: input.confidence ?? current.confidence ?? null, status: input.status ?? current.status ?? "candidate", validFrom: input.validFrom === null ? null : input.validFrom?.toISOString() ?? current.validFrom?.toISOString() ?? null, validTo: input.validTo === null ? null : input.validTo?.toISOString() ?? current.validTo?.toISOString() ?? null, propertiesJson: JSON.stringify(input.properties ?? current.properties), updatedAt: new Date().toISOString() }; const result = await this.query("MATCH ()-[r:UP_EDGE {id:$id,scopeId:$scopeId}]->() SET r += $value RETURN r AS edge", { id, scopeId: scopeId(input.scope), value: next }); return result.records[0] ? toEdge(result.records[0].get("edge")) : null; }
  async deleteEdge(id: string, scope?: PlanetScope): Promise<boolean> { const scopeKey = scopeId(scope); await this.query("MATCH (e:UPEvidence {edgeId:$id,scopeId:$scopeId}) DETACH DELETE e", { id, scopeId: scopeKey }); const result = await this.query("MATCH ()-[r:UP_EDGE {id:$id,scopeId:$scopeId}]->() DELETE r RETURN count(*) AS count", { id, scopeId: scopeKey }); return Number(result.records[0]?.get("count") ?? 0) > 0; }
  async neighbors(input: NeighborsInput): Promise<GraphEdge[]> { const direction = input.direction ?? "both"; const match = direction === "outbound" ? "(n)-[r:UP_EDGE]->(m)" : direction === "inbound" ? "(m)-[r:UP_EDGE]->(n)" : "(n)-[r:UP_EDGE]-(m)"; const result = await this.query(`MATCH ${match} WHERE n.id=$nodeId AND n.scopeId=$scopeId AND r.scopeId=$scopeId AND ($relation IS NULL OR r.relation=$relation) AND ($asOf IS NULL OR r.validFrom IS NULL OR r.validFrom<=$asOf) AND ($asOf IS NULL OR r.validTo IS NULL OR r.validTo>$asOf) RETURN r AS edge ORDER BY r.createdAt,r.id LIMIT toInteger($limit)`, { nodeId: input.nodeId, scopeId: scopeId(input.scope), relation: input.relation ?? null, asOf: input.asOf?.toISOString() ?? null, limit: Math.max(1, Math.min(input.limit ?? 100, 10000)) }); return result.records.map((record) => toEdge(record.get("edge"))); }
  async traverse(input: TraverseInput): Promise<GraphTraversal> { const max = Math.max(1, Math.min(input.limit ?? 1000, 10000)); const depths = new Map(input.startIds.slice(0, max).map((id) => [id, 0])); const edges = new Map<string, GraphEdge>(); let frontier = [...depths.keys()]; for (let depth = 1; depth <= input.depth && frontier.length && depths.size < max; depth++) { const next: string[] = []; for (const id of frontier) for (const edge of await this.neighbors({ nodeId: id, direction: input.direction, relation: input.relation, asOf: input.asOf, limit: max, scope: input.scope })) { edges.set(edge.id, edge); const target = edge.sourceId === id ? edge.targetId : edge.sourceId; if (!depths.has(target) && depths.size < max) { depths.set(target, depth); next.push(target); } } frontier = next; } const nodes = (await Promise.all([...depths.keys()].map((id) => this.getNode(id, input.scope)))).filter((item): item is GraphNode => item !== null); return { nodes, edges: [...edges.values()], depthByNode: Object.fromEntries(depths) }; }
  async searchNodes(input: { query: string; limit?: number; scope?: PlanetScope }): Promise<GraphNode[]> { const result = await this.query("MATCH (n:UPNode {scopeId:$scopeId}) WHERE toLower(n.name) CONTAINS toLower($query) RETURN n AS node ORDER BY n.name,n.id LIMIT toInteger($limit)", { scopeId: scopeId(input.scope), query: input.query, limit: Math.max(1, Math.min(input.limit ?? 20, 1000)) }); return result.records.map((record) => toNode(record.get("node"))); }
}

export class Neo4jEvidenceStore extends Neo4jStore implements EvidenceStore {
  constructor(driver: Neo4jDriver, database?: string, namespaces: Neo4jNamespaces = {}) { super(driver, database, namespaces); }
  async add(input: AddEvidenceInput): Promise<Evidence> { if (!input.documentId && !input.sourceId) throw new Error("Evidence requires a documentId or sourceId."); const value = { id: input.id ?? crypto.randomUUID(), scopeId: scopeId(input.scope), edgeId: input.edgeId, documentId: input.documentId ?? null, sourceId: input.sourceId ?? null, chunkId: input.chunkId ?? null, sourceType: input.sourceType ?? null, extractor: input.extractor, confidence: input.confidence ?? null, direction: input.direction ?? "support", strength: input.strength ?? input.confidence ?? null, metadataJson: JSON.stringify(input.metadata ?? {}), createdAt: new Date().toISOString() }; const result = await this.query("MATCH ()-[r:UP_EDGE {id:$edgeId,scopeId:$scopeId}]->() CREATE (e:UPEvidence $value) RETURN e AS evidence", { edgeId: input.edgeId, scopeId: value.scopeId, value }); if (!result.records[0]) throw new Error("Evidence requires an existing edge in this scope."); return toEvidence(result.records[0].get("evidence")); }
  async list(input: EvidenceListInput): Promise<Evidence[]> { const where = ["e.scopeId=$scopeId"]; const params: Record<string, unknown> = { scopeId: scopeId(input.scope), limit: Math.max(1, Math.min(input.limit ?? 100, 10000)) }; if (input.edgeId) { where.push("e.edgeId=$edgeId"); params.edgeId = input.edgeId; } if (input.edgeIds?.length) { where.push("e.edgeId IN $edgeIds"); params.edgeIds = input.edgeIds; } if (input.documentId) { where.push("e.documentId=$documentId"); params.documentId = input.documentId; } if (input.sourceId) { where.push("e.sourceId=$sourceId"); params.sourceId = input.sourceId; } const result = await this.query(`MATCH (e:UPEvidence) WHERE ${where.join(" AND ")} RETURN e AS evidence ORDER BY e.createdAt,e.id LIMIT toInteger($limit)`, params); return result.records.map((record) => toEvidence(record.get("evidence"))); }
  async listPage(input: EvidenceListInput & { afterId?: string }): Promise<{ items: Evidence[]; hasMore: boolean }> {
    const limit = Math.max(1, Math.min(input.limit ?? 100, 500));
    const where = ["e.scopeId=$scopeId"];
    const params: Record<string, unknown> = { scopeId: scopeId(input.scope), limit: limit + 1 };
    if (input.edgeId) { where.push("e.edgeId=$edgeId"); params.edgeId = input.edgeId; }
    if (input.edgeIds?.length) { where.push("e.edgeId IN $edgeIds"); params.edgeIds = input.edgeIds; }
    if (input.documentId) { where.push("e.documentId=$documentId"); params.documentId = input.documentId; }
    if (input.sourceId) { where.push("e.sourceId=$sourceId"); params.sourceId = input.sourceId; }
    if (input.afterId) { where.push("e.id>$afterId"); params.afterId = input.afterId; }
    const result = await this.query(`MATCH (e:UPEvidence) WHERE ${where.join(" AND ")} RETURN e AS evidence ORDER BY e.id LIMIT toInteger($limit)`, params);
    return { items: result.records.slice(0, limit).map((record) => toEvidence(record.get("evidence"))), hasMore: result.records.length > limit };
  }
  async deleteByDocument(input: { documentId: string; scope?: PlanetScope }): Promise<number> { const result = await this.query("MATCH (e:UPEvidence {scopeId:$scopeId,documentId:$documentId}) WITH collect(e) AS values FOREACH (value IN values | DETACH DELETE value) RETURN size(values) AS count", { scopeId: scopeId(input.scope), documentId: input.documentId }); return Number(result.records[0]?.get("count") ?? 0); }
  async deleteByChunks(input: { chunkIds: string[]; scope?: PlanetScope }): Promise<number> { if (!input.chunkIds.length) return 0; const result = await this.query("MATCH (e:UPEvidence {scopeId:$scopeId}) WHERE e.chunkId IN $chunkIds WITH collect(e) AS values FOREACH (value IN values | DETACH DELETE value) RETURN size(values) AS count", { scopeId: scopeId(input.scope), chunkIds: input.chunkIds }); return Number(result.records[0]?.get("count") ?? 0); }
}

export async function initializeNeo4jSchema(driver: Neo4jDriver, database?: string, namespaces: ProviderSchemaMap = {}): Promise<void> { const labels = neo4jLabels(namespaces); const nodeIndex = namespaces.graph ? `${namespaces.graph}_up_node_scope_id` : "up_node_scope_id"; const edgeIndex = namespaces.graph ? `${namespaces.graph}_up_edge_scope_id` : "up_edge_scope_id"; const evidenceIndex = namespaces.evidence ? `${namespaces.evidence}_up_evidence_scope_id` : "up_evidence_scope_id"; const session = driver.session(database ? { database } : undefined); try { await session.run(`CREATE CONSTRAINT ${nodeIndex} IF NOT EXISTS FOR (n:${labels.UPNode}) REQUIRE (n.scopeId,n.id) IS UNIQUE`); await session.run(`CREATE INDEX ${edgeIndex} IF NOT EXISTS FOR ()-[r:${labels.UP_EDGE}]-() ON (r.scopeId,r.id)`); await session.run(`CREATE INDEX ${evidenceIndex} IF NOT EXISTS FOR (e:${labels.UPEvidence}) ON (e.scopeId,e.id)`); } finally { await session.close(); } }
export function createNeo4jProvider(input: { id?: string; driver: Neo4jDriver; database?: string; schemas?: ProviderSchemaMap }): DataLayerProvider { const namespaces = { graph: input.schemas?.graph, evidence: input.schemas?.evidence }; neo4jLabels(namespaces); return { id: input.id ?? "neo4j", graph: new Neo4jGraphStore(input.driver, input.database, namespaces), evidence: new Neo4jEvidenceStore(input.driver, input.database, namespaces) }; }
